version: '3'
services:
  payara:
    build: ../images/payara
    environment:
     - ADMIN_PASSWORD=adminadmin
    ports:
     - "9090:8080"
     - "3838:4848"
    links:
     - mysql:db
  mysql:
    build: ../images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "6060:80"
    links:
     - mysql:db
