version: '3'

services:
  
  payara:
    build: ../images/payara
    environment:
      PAYARA_ARGS: "--debug"
    ports:
      - 9090:8080
      - 3838:4848
      - 9009:9009

  db:
    build: ../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
    restart: always
    depends_on:
     - db
    ports:
     - 8888:80
