version: '3'
services:
  payara:
    build: ../images/payara
    environment:
      - ADMIN_PASSWORD=adminadmin
    links:
      - mysql:db
    ports:
      - "8080:8080"
      - "4848:4848"
  mysql:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"